version: "2.1"
services:
  web:
    image: nginx
    volumes:
      - ${PWD}/html:/usr/share/nginx/html:ro
    ports: 
      - "8083:80"
    #environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80